server:
  host: "0.0.0.0"
  port: 8000

postgres:
  dsn: "postgresql://user:pass@localhost:5432/postgres"
  pool_min: 2
  pool_max: 8
  statement_timeout_ms: 600000

duckdb:
  memory_limit: "8GB"
  threads: 8
  cache_ttl_seconds: 900
  persistent_enabled: true
  persistent_path: "cache.duckdb"

cache:
  max_tables: 2000
  max_rows_per_table: 5000000

invalidator:
  enabled: true
  check_interval_seconds: 60
  query: "SELECT COALESCE(MAX(updated_at)::text, '0') FROM public.data_updates"

security:
  allow_raw_select_only: true
  forbid_semicolons: true

logging:
  sql_log_top_k: 100

hypercube:
  allowed_dimensions: ["p1","p2","p3"]
  measure: "count"
  source_table: "public.facts_agg"
  base_where: ""
  max_dimensionality: 3
